// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBF1NTcoq0_MXUPr5xWjqsCn_57ieT4Cg8',
    appId: '1:1019146773543:web:4bb3573f735b0a14091a02',
    messagingSenderId: '1019146773543',
    projectId: 'safepass-d5403',
    authDomain: 'safepass-d5403.firebaseapp.com',
    storageBucket: 'safepass-d5403.firebasestorage.app',
    measurementId: 'G-4S3VDKFVHJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6apmmu-7SLac4tm326mQY5L8iArOoYTE',
    appId: '1:1019146773543:android:3a55b400ef96c326091a02',
    messagingSenderId: '1019146773543',
    projectId: 'safepass-d5403',
    storageBucket: 'safepass-d5403.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNtHDsaJmf4drDnQJIinBsdzJZ5feGa4E',
    appId: '1:1019146773543:ios:ffd82189dd440ad0091a02',
    messagingSenderId: '1019146773543',
    projectId: 'safepass-d5403',
    storageBucket: 'safepass-d5403.firebasestorage.app',
    iosClientId: '1019146773543-iaruebgvebdk0tg4epfmsk4o4o84hok0.apps.googleusercontent.com',
    iosBundleId: 'com.safepass-tech.safepassMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNtHDsaJmf4drDnQJIinBsdzJZ5feGa4E',
    appId: '1:1019146773543:ios:ffd82189dd440ad0091a02',
    messagingSenderId: '1019146773543',
    projectId: 'safepass-d5403',
    storageBucket: 'safepass-d5403.firebasestorage.app',
    iosClientId: '1019146773543-iaruebgvebdk0tg4epfmsk4o4o84hok0.apps.googleusercontent.com',
    iosBundleId: 'com.safepass-tech.safepassMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBF1NTcoq0_MXUPr5xWjqsCn_57ieT4Cg8',
    appId: '1:1019146773543:web:438a499e78866044091a02',
    messagingSenderId: '1019146773543',
    projectId: 'safepass-d5403',
    authDomain: 'safepass-d5403.firebaseapp.com',
    storageBucket: 'safepass-d5403.firebasestorage.app',
    measurementId: 'G-QZZBE7DB27',
  );

}